version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/ErunJrun_BE

hooks:
#     ApplicationStop:
#         - location: scripts/stop.sh
#           runas: root
    AfterInstall:
        - location: scripts/after.deploy.sh
#     ApplicationStart:
#         - location: scripts/start.sh
#           runas: root
